### ISSUE TITLE
Add share window for better UX

### ISSUE THREAD

**Issue by justinkemerling** [jakewelchert/dcd#33]
<img width="668" alt="screen shot 2017-06-26 at 2 55 17 pm" src="https://user-images.githubusercontent.com/5384728/27558294-87b5f3c2-5a82-11e7-9074-e478cc121574.png">

**Comment by jakewelchert** [comment]
1. Add necessary pop-up script (see below)
2. Add **class='share'** to the a tags on the share buttons

<script>
;(function($){
  
  /**
   * jQuery function to prevent default anchor event and take the href * and the title to make a share popup
   *
   * @param  {[object]} e           [Mouse event]
   * @param  {[integer]} intWidth   [Popup width defalut 500]
   * @param  {[integer]} intHeight  [Popup height defalut 400]
   * @param  {[boolean]} blnResize  [Is popup resizeabel default true]
   */
  $.fn.customerPopup = function (e, intWidth, intHeight, blnResize) {
    
    // Prevent default anchor event
    e.preventDefault();
    
    // Set values for window
    intWidth = intWidth || '500';
    intHeight = intHeight || '400';
    strResize = (blnResize ? 'yes' : 'no');

    // Set title and open popup with focus on it
    var strTitle = ((typeof this.attr('title') !== 'undefined') ? this.attr('title') : 'Social Share'),
        strParam = 'width=' + intWidth + ',height=' + intHeight + ',resizable=' + strResize,            
        objWindow = window.open(this.attr('href'), strTitle, strParam).focus();
  }
  
  /* ================================================== */
  
  $(document).ready(function ($) {
    $('.share').on("click", function(e) {
      $(this).customerPopup(e);
    });
  });
    
}(jQuery));
</script>

**Comment by alexpgates** [comment]
@jakewelchert 
This works just fine for Twitter share links, but the Facebook popup immediately closes for me. I don't know if this is Facebook preventing this share popup stuff or if it's related to something else in the code.

The code you pasted was minified, so the comments were commenting out code.. I went through and updated the code:

`;(function($){ $.fn.customerPopup = function (e, intWidth, intHeight, blnResize) { e.preventDefault(); intWidth = intWidth || '500'; intHeight = intHeight || '400'; strResize = (blnResize ? 'yes' : 'no'); var strTitle = ((typeof this.attr('title') !== 'undefined') ? this.attr('title') : 'Social Share'), strParam = 'width=' + intWidth + ',height=' + intHeight + ',resizable=' + strResize, objWindow = window.open(this.attr('href'), strTitle, strParam).focus(); }
$(document).ready(function ($) { $('.share, .share-post').on("click", function(e) { $(this).customerPopup(e); }); }); }(jQuery));`

to remove the comments in order to prevent legit code from being commented out.

**Comment by justinkemerling** [comment]
Facebook also closes for me. And also, News posts share nicely, but the others (Events + Candidates + Elected Officials) don't pulled in the title text:

![screen shot 2017-06-29 at 6 46 37 pm](https://user-images.githubusercontent.com/5384728/27715229-6a168374-5cfb-11e7-980b-5047dcce8a15.png)

**Comment by jakewelchert** [comment]
Alright, most of the strange spacing is due to this share issue. Alex, here's a link to a Codepen that I've pulled this share code from in the past: https://codepen.io/patrickkahl/pen/DxmfG

We can change the class that I had you add yesterday from **share** to **share-popup** and it should fix this since there must've been a class with the name of share already.

You'll also need to change the class being called in the Codepen javascript from **.customer.share** to **.share-popup**

![screen shot 2017-06-30 at 9 26 02 am](https://user-images.githubusercontent.com/3301072/27740041-3fc744d4-5d76-11e7-975f-237c691ea8fd.png)

**Comment by alexpgates** [comment]
Okay - the class names appear to have fixed the spacing issue. I had adjusted the javascript class yesterday, but tweaked it again now to reflect the new css class.
I'm still running in to the issue of the Facebook share dialogue closing immediately. Are you still having that issue, @justinkemerling?

**Comment by alexpgates** [comment]
@justinkemerling I think I found and fixed the issue with the events, candidates, and elected officials share buttons not containing the proper URL / text. 
It was working fine on news, but these other post types weren't pulling that stuff in.

If you have a second, please double check the sharing stuff on all these different post types to make sure we're getting the right content in those share dialogues.

**Comment by justinkemerling** [comment]
I think this is good. FB is still having some opening issues but maybe that's because it hasn't been shared there yet?

<img width="301" alt="screen shot 2017-06-30 at 11 20 21 am" src="https://user-images.githubusercontent.com/5384728/27744698-282428be-5d86-11e7-86a7-474c067bbffe.png">

**Comment by justinkemerling** [comment]
Probably a password protect thing. Will check again after launch.
